FROM alpine:3.7 AS python_builder

ENV LANG C.UTF-8
ENV GPG_KEY E3FF2839C048B25C084DEBE9B26995E310250568
ENV PYTHON_VERSION 3.9.0

# Based on https://github.com/docker-library/python/blob/master/3.9/alpine3.12/Dockerfile
RUN set -ex \
    && apk add --no-cache ca-certificates tzdata \
	&& apk add --no-cache --virtual .fetch-deps \
		gnupg \
		tar \
		xz

RUN set -ex \
	&& wget -O python.tar.xz "https://www.python.org/ftp/python/${PYTHON_VERSION%%[a-z]*}/Python-$PYTHON_VERSION.tar.xz" \
	&& wget -O python.tar.xz.asc "https://www.python.org/ftp/python/${PYTHON_VERSION%%[a-z]*}/Python-$PYTHON_VERSION.tar.xz.asc" \
	&& export GNUPGHOME="$(mktemp -d)" \
	&& gpg --batch --keyserver ha.pool.sks-keyservers.net --recv-keys "$GPG_KEY" \
	&& gpg --batch --verify python.tar.xz.asc python.tar.xz \
	&& { command -v gpgconf > /dev/null && gpgconf --kill all || :; } \
	&& rm -rf "$GNUPGHOME" python.tar.xz.asc \
	&& mkdir -p /usr/src/python \
	&& tar -xJC /usr/src/python --strip-components=1 -f python.tar.xz \
	&& rm python.tar.xz

RUN set -ex \
	&& apk add --no-cache --virtual .build-deps  \
		bluez-dev \
		bzip2-dev \
        libbz2 \
        libnsl-dev \
		coreutils \
        perl \
		dpkg-dev dpkg \
		expat-dev \
		findutils \
		gcc \
        g++ \
		gdbm-dev \
		libc-dev \
		libffi-dev \
		libtirpc-dev \
		linux-headers \
		make \
		ncurses-dev \
		pax-utils \
		readline-dev \
		sqlite-dev \
		tcl-dev \
		tk \
		tk-dev \
		util-linux-dev \
		xz-dev \
		zlib-dev \
# add build deps before removing fetch deps in case there's overlap
	&& apk del --no-network .fetch-deps

RUN wget -O openssl-1.1.1h.tar.gz https://www.openssl.org/source/openssl-1.1.1h.tar.gz \
    && echo "da50fd99325841ed7a4367d9251c771ce505a443a73b327d8a46b2c6a7d2ea99e43551a164efc86f8743b22c2bdb0020bf24a9cbd445e9d68868b2dc1d34033a  openssl-1.1.1h.tar.gz" > sums \
    && sha512sum -c sums \
    && tar xzf openssl-1.1.1h.tar.gz \
    && cd openssl-1.1.1h \
    && perl ./Configure linux-x86_64 --prefix=/usr/local/ \
        --libdir=lib \
        --openssldir=/usr/local/etc/ssl \
        shared no-zlib enable-ec_nistp_64_gcc_128 \
        no-async no-comp no-idea no-mdc2 no-rc5 no-ec2m \
        no-sm2 no-sm4 no-ssl2 no-ssl3 no-seed \
        no-weak-ssl-ciphers \
        -fPIC -Wa,--noexecstack \
    && make \
    && make install_sw


RUN set -ex \
	&& cd /usr/src/python \
	&& gnuArch="$(dpkg-architecture --query DEB_BUILD_GNU_TYPE)" \
	&& ./configure \
		--build="$gnuArch" \
        --enable-ipv6 \
		--enable-shared \
		--enable-optimizations \
        --with-lto \
		--without-ensurepip \
	&& make -j "$(nproc)" \
# set thread stack size to 1MB so we don't segfault before we hit sys.getrecursionlimit()
# https://github.com/alpinelinux/aports/commit/2026e1259422d4e0cf92391ca2d3844356c649d0
		EXTRA_CFLAGS="-DTHREAD_STACK_SIZE=0x100000" \
		LDFLAGS="-Wl,--strip-all" \
	&& make install \
	&& rm -rf /usr/src/python

RUN set -ex \
	&& find /usr/local -depth \
		\( \
			\( -type d -a \( -name test -o -name tests -o -name idle_test \) \) \
			-o \( -type f -a \( -name '*.pyc' -o -name '*.pyo' -o -name '*.a' \) \) \
		\) -exec rm -rf '{}' + \
	\
	&& find /usr/local -type f -executable -not \( -name '*tkinter*' \) -exec scanelf --needed --nobanner --format '%n#p' '{}' ';' \
		| tr ',' '\n' \
		| sort -u \
		| awk 'system("[ -e /usr/local/lib/" $1 " ]") == 0 { next } { print "so:" $1 }' \
		| xargs -rt apk add --no-cache --virtual .python-rundeps \
	&& apk del --no-network .build-deps \
	\
	&& python3 --version

# make some useful symlinks that are expected to exist
RUN cd /usr/local/bin \
	&& ln -s idle3 idle \
	&& ln -s pydoc3 pydoc \
	&& ln -s python3 python \
	&& ln -s python3-config python-config

# if this is called "PIP_VERSION", pip explodes with "ValueError: invalid truth value '<VERSION>'"
ENV PYTHON_PIP_VERSION 20.3.1
# https://github.com/pypa/get-pip
ENV PYTHON_GET_PIP_URL https://github.com/pypa/get-pip/raw/91630a4867b1f93ba0a12aa81d0ec4ecc1e7eeb9/get-pip.py
ENV PYTHON_GET_PIP_SHA256 d48ae68f297cac54db17e4107b800faae0e5210131f9f386c30c0166bf8d81b7

RUN set -ex; \
	\
	wget -O get-pip.py "$PYTHON_GET_PIP_URL"; \
	echo "$PYTHON_GET_PIP_SHA256 *get-pip.py" | sha256sum -c -; \
	\
	python get-pip.py \
		--disable-pip-version-check \
		--no-cache-dir \
		"pip==$PYTHON_PIP_VERSION" \
	; \
	pip --version; \
	\
	find /usr/local -depth \
		\( \
			\( -type d -a \( -name test -o -name tests -o -name idle_test \) \) \
			-o \
			\( -type f -a \( -name '*.pyc' -o -name '*.pyo' \) \) \
		\) -exec rm -rf '{}' +; \
	rm -f get-pip.py


# Heavily based on https://github.com/six8/pyinstaller-alpine/
FROM alpine:3.7

LABEL maintainer="Barracuda Networks"
ARG PYINSTALLER_TAG=v4.1
ENV PATH /usr/local/bin:$PATH

ENV LANG C.UTF-8
ENV PYTHON_VERSION 3.9.0

COPY --from=python_builder /usr/local /usr/local

RUN set -eux; \
    apk --update --no-cache add \
    zlib-dev \
    musl-dev \
    libc-dev \
    libffi-dev \
    bzip2-dev \
    libbz2 \
    libnsl-dev \
    gdbm-dev \
    libtirpc-dev \
    linux-headers \
    make \
    ncurses-dev \
    pax-utils \
    readline-dev \
    sqlite-dev \
    util-linux-dev \
    xz-dev \
    dpkg-dev dpkg \
    expat-dev \
    coreutils \
    findutils \
    gcc \
    g++ \
    git \
    pwgen \
    ca-certificates \
    tzdata \
    gettext \
    && pip install --upgrade pip \
    && pip install certifi pycrypto \
    && rm -rf /var/cache/apk/*

RUN git clone --depth 1 --single-branch --branch ${PYINSTALLER_TAG} https://github.com/pyinstaller/pyinstaller.git /tmp/pyinstaller \
    && cd /tmp/pyinstaller/bootloader \
    && CFLAGS="-Wno-stringop-overflow -Wno-stringop-truncation" python ./waf configure --no-lsb all \
    && pip install .. \
    && rm -Rf /tmp/pyinstaller \
    && rm -Rf /root/.cache

COPY alpine-bin/ /usr/local/bin
RUN chmod +x /usr/local/bin/*
