#!/bin/sh

SDK=kits\\10
SDK_UNIX=kits/10
BASE=z:\\opt\\msvc
BASE_UNIX=/opt/msvc
MSVCVER=14.28.29910
SDKVER=10.0.19041.0
ARCH=x64
MSVCDIR="$BASE\\vc\\tools\\msvc\\$MSVCVER"
SDKINCLUDE="$BASE\\$SDK\\include\\$SDKVER"
SDKLIB="$BASE\\$SDK\\lib\\$SDKVER"
BINDIR=$BASE_UNIX/vc/tools/msvc/$MSVCVER/bin/Hostx64/$ARCH
SDKBINDIR=$BASE_UNIX/$SDK_UNIX/bin/$SDKVER/x64
WINESDKBINDIR="$BASE\\$SDK\\bin\\$SDKVER\\x64"
export INCLUDE="$MSVCDIR\\include;$SDKINCLUDE\\shared;$SDKINCLUDE\\ucrt;$SDKINCLUDE\\um;$SDKINCLUDE\\winrt;$SDKINCLUDE\\cppwinrt"
export LIB="$MSVCDIR\\lib\\$ARCH;$SDKLIB\\ucrt\\$ARCH;$SDKLIB\\um\\$ARCH;$BASE\\$SDK\\UnionMetadata\\$SDKVER;$BASE\\$SDK\\References\\$SDKVER"
export LIBPATH="$LIB"
export WINEPATH="${BINDIR//\//\\};${SDKBINDIR//\//\\};$MSVCDIR\\bin\\Hostx64\\x64;$WINESDKBINDIR"
export ExtensionSdkDir="$BASE\\$SDK\\Extension\ SDKs"
export Platform=x64
export PROCESSOR_ARCHITECTURE=AMD64
export UCRTVersion=$SDKVER
export UniversalCRTSdkDir="$BASE\\$SDK"
export VCINSTALLDIR="$BASE\\VC"
export VCToolsInstallDir="$MSVCDIR"
export VCToolsRedistDir="$BASE\\vc\\Redist\\MSVC\\$MSVCVER"
export VCToolsVersion=$MSVCVER
export VisualStudioVersion=16.0
export VSCMD_ARG_app_plat=Desktop
export VSCMD_ARG_HOST_ARCH=x64
export VSCMD_ARG_TGT_ARCH=x64
export VSCMD_VER=16.9.0
export VSINSTALLDIR="$BASE"
export WindowsLibPath="$BASE\\$SDK\\UnionMetadata\\$SDKVER;$BASE\\$SDK\\References\\$SDKVER"
export WindowsSdkBinPath="$BASE\\$SDK\\bin"
export WindowsSdkDir="$BASE\\$SDK"
export WindowsSDKLibVersion="$SDKVER"
export WindowsSdkVerBinPath="$WINESDKBINDIR"
export WindowsSDKVersion=$SDKVER
export __DOTNET_ADD_64BIT=1
export __DOTNET_PREFERRED_BITNESS=64
